name: Staging

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, review_requested]

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      container_digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Setup the current date
        id: prep
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: marshallasch/socis
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
  deploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@v1.21.2
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/site website=marshallasch/socis@${{ needs.docker.outputs.container_digest }} --namespace "socis-website"
